# Generated by Django 4.1 on 2023-10-05 16:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID of this user', primary_key=True, serialize=False),
        ),
    ]
