# Generated by Django 4.1 on 2023-10-05 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_alter_person_salary'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='city',
            table='city',
        ),
    ]
